general:
  useProductionCerts: true
  projectId: may-awesome-project
  dockerconfigjson: SealedCredentialsForDockerCOntainerRegistry
  imagePullSecrets: ckan-sealed-registry
  customResource: true
  resources: {}
  maintenance: false

ingress:
  enable: true
  enableExternal: false
  enableExternalCertificate: false
  hosts:
    - host: ckan.my-awesome-project.staging.datopian.com
      isExternal: false
      paths:
        - path: /(.*)
          service: may-awesome-project-ckan-svc
          port: 80
    - host: my-awesome-project.staging.datopian.com
      isExternal: false
      paths:
        - path: /(.*)
          service: may-awesome-project-frontend-svc
          port: web
  tls:
    - secretName: ckan.my-awesome-project.staging.datopian.com
      hosts:
        - ckan.my-awesome-project.staging.datopian.com
    - secretName: my-awesome-project.staging.datopian.com
      hosts:
        - my-awesome-project.staging.datopian.com

solr:
  enable: true
  resources:
    limits:
      cpu: 100m
      memory: 1G
    requests:
      cpu: 70m
      memory: 800M
  image:
    tag: 6.6.6

ckan:
  useIni:
    enable: false
    iniPath: "/srv/app/production.ini"
  hpa:
    enable: false
  resources:
    limits:
      cpu: 250m
      memory: 1.2G
    requests:
      cpu: 200m
      memory: 1G
  image:
    repository: viderum/ckan
    pullPolicy: Always
    tag: 2.9.5
  service:
    type: ClusterIP
    port: 80
  env:
   EXAMPLE_ENV: ""

frontend:
  enable: false
  image:
    repository: datopian/frontend
    tag: latest
    pullPolicy: Always
  hpa:
    enable: false
  resources:
    limits:
      cpu: 250m
      memory: 1.2G
    requests:
      cpu: 200m
      memory: 1G

datapusher:
  enable: true
  image:
    repository: datopian/datapusher
    tag: latest
    pullPolicy: Always
  hpa:
    enable: false

dataSubscriptions:
  enable: false
  image:
    repository: datopian/data-subscriptions
    tag: latest
    pullPolicy: Always

auth:
  enable: false
  image:
    repository: datopian/auth
    tag: latest
    pullPolicy: Always

giftless:
  enable: false
  image:
    repository: datopian/giftless
    tag: 0.1.2

postgresql:
  enable: false

xloader:
  enable: false

dbBackup:
  enable: false

ckanmiddleware:
  enable: false
