apiVersion: v1
entries:
  ckan:
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-07-29T13:20:04.401097817Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: fbc3f466bbc1508f1b257f2706baddfb027a56485780c9dac2c16e7bc520bf26
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.3.3.tgz
    version: v1.3.3
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-07-29T13:20:04.388696963Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 8290c64152f308afe692359108ace4fdbdd503e0de83d15efe855b4e4ad6a45b
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-1.3.0.tgz
    version: 1.3.0
generated: "2021-07-29T13:20:04.380842786Z"
