apiVersion: v1
entries:
  ckan:
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.732150168+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 108456b9779b61f45c20145408ab30b4b186bf7ccb261cb2604c40587d20ee33
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v2.1.1.tgz
    version: v2.1.1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.647548985+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 8a1a6a0cdc5b032e8d50847b84537c9a121fb5d3054df872f617e8f1f23f3c2d
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.642155867+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 0ab326dc6e739ff2e27324d1d4015126133ca23007f1004a529e9dcce4766d0b
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-2.0.3.tgz
    version: 2.0.3
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.727395222+05:00"
    dependencies:
    - name: solr
      repository: https://charts.bitnami.com/bitnami
      version: 2.0.6
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 16486d8c00fb44e3fb53e0124c1dbc0f65b12e820a02033cb61eb52a35d0be91
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.5.0-rc1.tgz
    version: v1.5.0-rc1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.678595149+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 902bfca8bcf2ee373389eb49dcdc012e02eccddb5745c8d184eac0cfcd9c2154
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.10.tgz
    version: v1.4.10
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.71910383+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: c436d940f84f305de00aafff2ee74b43287ab8405c5d5e959f6647a0fef56ae8
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.9.tgz
    version: v1.4.9
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.71345164+05:00"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 16f105ac3c21e45bca1c992f71430e40b06be110b019a603c82dd177f3860a17
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.8.tgz
    version: v1.4.8
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.708637358+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 340a2253c662b9e99acf8e5edf33365d4107bfea9a04b8969677107194a80db2
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.7.tgz
    version: v1.4.7
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.703341402+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: ddc8df88816063607e4b66b7e2374d097384525d0b883417f583da17d134284a
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.6-rc0.tgz
    version: v1.4.6-rc0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.698664315+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: a098551fb7b07beab3728d611918330176f4dbb66bf0d68516181dd63ffd01e3
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.5.tgz
    version: v1.4.5
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.693446137+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 62a4079fba25bcd8ebab8fca19d5a4537ab915cf4c8b660eef8fd5b3a2d8db6e
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.4.tgz
    version: v1.4.4
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.688259952+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 4954cadc23eddf06a11bd9c2fd33f8f91e207535438df9c449bc8663244ae2a1
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.3.tgz
    version: v1.4.3
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.683724756+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 1e7a7a6e77da3b6aa4795268ef3149d271a9b46c0ee69909ce3f6becb6273635
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.2.tgz
    version: v1.4.2
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.673968885+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: b45d3aab59237198bc148980fe6f7965f1fefd5821802a37e38ad909f40f35d0
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.668436289+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: e697464713944230978a901ef9156c70522fb8db25868e10586bb38935ef0469
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.663590981+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: c9a8c1fd0d04562102fbfdcdf25582c6e7323c1a5868b598b47e7ced69200a0e
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.0-rc6.tgz
    version: v1.4.0-rc6
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.65804626+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 87dc63a1d23e2b416740ee1b2b40f2ba14e5906b9e4dfebd8ff2ba6761cd7426
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.4.0-rc1.tgz
    version: v1.4.0-rc1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2022-06-13T14:07:05.653128775+05:00"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 5af8e4655d7e4b84a49e6c18a629c8e5e6496c81495e89f83b199b6fa6c7fee9
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/enable_ghost/charts/ckan-v1.3.0.tgz
    version: v1.3.0
generated: "2022-06-13T14:07:05.636794095+05:00"
