apiVersion: v1
entries:
  ckan:
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-08-09T07:32:45.52988157Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: b45d3aab59237198bc148980fe6f7965f1fefd5821802a37e38ad909f40f35d0
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-08-09T07:32:45.523810692Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: e697464713944230978a901ef9156c70522fb8db25868e10586bb38935ef0469
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-08-09T07:32:45.51716609Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: c9a8c1fd0d04562102fbfdcdf25582c6e7323c1a5868b598b47e7ced69200a0e
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0-rc6.tgz
    version: v1.4.0-rc6
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-08-09T07:32:45.508899375Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 87dc63a1d23e2b416740ee1b2b40f2ba14e5906b9e4dfebd8ff2ba6761cd7426
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0-rc1.tgz
    version: v1.4.0-rc1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-08-09T07:32:45.502274505Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 5af8e4655d7e4b84a49e6c18a629c8e5e6496c81495e89f83b199b6fa6c7fee9
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.3.0.tgz
    version: v1.3.0
generated: "2021-08-09T07:32:45.493911135Z"
