apiVersion: v1
entries:
  ckan:
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.896659352Z"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: e7d1780f413c3df8e76f7a52ba05d27e58257e7bb8353b5d5ee476ef84aa7991
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.6.0-rc5.tgz
    version: v1.6.0-rc5
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.888889456Z"
    dependencies:
    - name: solr
      repository: https://charts.bitnami.com/bitnami
      version: 2.0.6
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 16486d8c00fb44e3fb53e0124c1dbc0f65b12e820a02033cb61eb52a35d0be91
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.5.0-rc1.tgz
    version: v1.5.0-rc1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.80795556Z"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 902bfca8bcf2ee373389eb49dcdc012e02eccddb5745c8d184eac0cfcd9c2154
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.10.tgz
    version: v1.4.10
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.874213675Z"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: c436d940f84f305de00aafff2ee74b43287ab8405c5d5e959f6647a0fef56ae8
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.9.tgz
    version: v1.4.9
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.866349279Z"
    dependencies:
    - condition: solr.enable
      name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 16f105ac3c21e45bca1c992f71430e40b06be110b019a603c82dd177f3860a17
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.8.tgz
    version: v1.4.8
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.857098265Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 340a2253c662b9e99acf8e5edf33365d4107bfea9a04b8969677107194a80db2
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.7.tgz
    version: v1.4.7
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.849267368Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: ddc8df88816063607e4b66b7e2374d097384525d0b883417f583da17d134284a
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.6-rc0.tgz
    version: v1.4.6-rc0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.839824352Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: a098551fb7b07beab3728d611918330176f4dbb66bf0d68516181dd63ffd01e3
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.5.tgz
    version: v1.4.5
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.831669752Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 62a4079fba25bcd8ebab8fca19d5a4537ab915cf4c8b660eef8fd5b3a2d8db6e
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.4.tgz
    version: v1.4.4
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.823547552Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 4954cadc23eddf06a11bd9c2fd33f8f91e207535438df9c449bc8663244ae2a1
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.3.tgz
    version: v1.4.3
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.815247249Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 1e7a7a6e77da3b6aa4795268ef3149d271a9b46c0ee69909ce3f6becb6273635
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.2.tgz
    version: v1.4.2
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.79657502Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: b45d3aab59237198bc148980fe6f7965f1fefd5821802a37e38ad909f40f35d0
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.789213729Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: e697464713944230978a901ef9156c70522fb8db25868e10586bb38935ef0469
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.778948703Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: c9a8c1fd0d04562102fbfdcdf25582c6e7323c1a5868b598b47e7ced69200a0e
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0-rc6.tgz
    version: v1.4.0-rc6
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.770803002Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 87dc63a1d23e2b416740ee1b2b40f2ba14e5906b9e4dfebd8ff2ba6761cd7426
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.4.0-rc1.tgz
    version: v1.4.0-rc1
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2021-12-29T15:23:02.761850192Z"
    dependencies:
    - name: solr
      repository: http://storage.googleapis.com/kubernetes-charts-incubator
      version: 1.5.2
    - condition: postgresql.enable
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 9.1.4
    description: The world's leading Open Source data portal platform.
    digest: 5af8e4655d7e4b84a49e6c18a629c8e5e6496c81495e89f83b199b6fa6c7fee9
    name: ckan
    type: application
    urls:
    - https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ckan-v1.3.0.tgz
    version: v1.3.0
generated: "2021-12-29T15:23:02.752658779Z"
