{{- if .Values.auth.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-auth-envvars
{{- with .Values.auth.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
