{{ if .Values.general.env }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ckan-cloud-centeralized-sql
type: kubernetes.io/dockerconfigjson
data:
  POSTGRES_HOST: {{ .Values.global.env.POSTGRES_HOST | b64enc }}
  POSTGRES_SUPER_USER: {{ .Values.global.env.POSTGRES_SUPER_USER | b64enc }}
  POSTGRES_SUPER_USER_PASSWORD: {{ .Values.global.env.POSTGRES_SUPER_USER_PASSWORD | b64enc }}
{{ end }}
