{{- if .Values.dataSubscriptions.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-data-subscriptions-envvars
{{- with .Values.dataSubscriptions.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
