{{- $ds := (include "ckan.datastore" . | fromYaml) -}}
{{- if $ds.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-data-api-envvars
{{- with $ds.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}