{{- if .Values.dataAPI.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-data-api-envvars
{{- with .Values.dataAPI.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}