{{- if .Values.datapusher.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-datapusher-envvars
{{- with .Values.datapusher.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
