{{ if .Values.ingress.enableExternalCertificate }}
{{- range .Values.ingress.externalCertificate.hosts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .tlsSecret.name }}
  
type: kubernetes.io/tls
data:
  tls.crt: {{ .tlsSecret.crt  }}
  tls.key: {{ .tlsSecret.key  }}
---
{{- end }}
{{- end }}