{{- if .Values.frontend.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-frontend-envvars
{{- with .Values.frontend.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
