{{ if .Values.giftless.enable }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-giftless-envvars
{{- with .Values.giftless.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}

---

apiVersion: v1
data:
  jwt-rs256.key: {{ .Values.giftless.JwtRs256Key }}
  jwt-rs256.key.pub: {{ .Values.giftless.JwtRs256KeyPub }}
kind: Secret
metadata:
  name: jwt-keys
type: Opaque
{{ end }}
