{{- if .Values.hasura.enable -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.general.projectId }}-hasura-envvars
{{- with .Values.hasura.env }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}