{{ if .Values.dataSubscriptions.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.projectId }}-data-subscriptions-svc
spec:
  ports:
    - port: {{ .Values.dataSubscriptions.port | default 80 }}
      targetPort: {{ .Values.dataSubscriptions.targetPort | default 5500 }}
  selector:
    app: data-subscriptions
{{ end }}
