{{- $ds := (include "ckan.datastore" . | fromYaml) -}}
{{ if $ds.hpa.enable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.general.projectId }}-data-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.general.projectId }}-data-api
  minReplicas: {{ $ds.hpa.minReplicas | default 1 }}
  maxReplicas: {{ $ds.hpa.maxReplicas | default 3 }}
  metrics:
  {{ if $ds.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $ds.hpa.targetCPUUtilizationPercentage }}
  {{ end }}
  {{ if $ds.hpa.targetMemoryUtilizationPercentage}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $ds.hpa.targetMemoryUtilizationPercentage }}
  {{ end }}
{{ end }}
