{{- $ds := (include "ckan.datastore" . | fromYaml) -}}
{{ if $ds.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.projectId }}-data-api-svc
spec:
  type: {{ $ds.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ $ds.port | default 80 }}
      targetPort: {{ $ds.targetPort | default 3000 }}
      protocol: TCP
      name: http
  selector:
    app: data-api
{{ end }}


