{{- if .Values.datapusher.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.projectId }}-datapusher-svc
spec:
  ports:
  - port: {{ .Values.datapusher.port | default 80 }}
    targetPort: {{ .Values.datapusher.targetPort | default 8000 }}
  selector:
    app: datapusher
{{ end }}
