{{- $ds := (include "ckan.datastore" . | fromYaml) -}}
{{- if and $ds.spot $ds.spot.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.projectId }}-data-api-spot
  labels:
    app: data-api
    spot: "true"
spec:
  {{ if not $ds.spot.hpa.enable }}
  replicas: {{ $ds.spot.replicaCount | default 0 }}
  {{ end }}
  selector:
    matchLabels:
      app: data-api
      spot: "true"
  template:
    metadata:
      labels:
        app: data-api
        spot: "true"
    spec:
      terminationGracePeriodSeconds: {{ $ds.terminationGracePeriodSeconds | default 60 }}
      nodeSelector:
{{ toYaml $ds.spot.nodeSelector | nindent 8 }}
      tolerations:
{{ toYaml $ds.spot.tolerations | nindent 8 }}
      affinity:
{{ toYaml $ds.spot.affinity | nindent 8 }}
      {{ if .Values.general.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.general.imagePullSecrets }}
      {{ end }}
      containers:
        - name: data-api
          {{ if $ds.image.digest }}
          image: {{ $ds.image.repository | default "datopian/data-api" }}@{{ $ds.image.digest }}
          {{ else }}
          image: {{ $ds.image.repository | default "datopian/data-api" }}:{{ $ds.image.tag }}
          {{ end }}
          imagePullPolicy: {{ $ds.image.pullPolicy | default "Always" }}
          {{ if $ds.lifecycle }}
          lifecycle:
            {{ with $ds.lifecycle }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
          {{ else }}
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "{{ $ds.preStopSleepSeconds | default 15 }}"]
          {{ end }}
          {{ if $ds.env }}
          envFrom:
            - secretRef:
                name: {{ .Values.general.projectId }}-data-api-envvars
          {{ end }}
          {{ if $ds.livenessProbe }}
          livenessProbe:
            {{ with $ds.livenessProbe }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
          {{ end }}
          resources:
            {{ if $ds.spot.resources }}
            {{ with $ds.spot.resources }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
            {{ else if $ds.resources }}
            {{ with $ds.resources }}
            {{ toYaml . | nindent 12 }}
            {{ end }}
            {{ else }}
            limits:
              cpu: 600m
              memory: 1G
            requests:
              cpu: 100m
              memory: 0.8G
            {{ end }}
          ports:
            - containerPort: 3000
              protocol: TCP
{{ end }}
