{{ if .Values.datapusher.hpa.enable }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.general.projectId }}-datapusher-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.general.projectId }}-datapusher
  minReplicas: {{ .Values.datapusher.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.datapusher.hpa.maxReplicas | default 5 }}
  metrics:
  {{ if .Values.datapusher.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.datapusher.hpa.targetCPUUtilizationPercentage }}
  {{ end }}
  {{ if .Values.datapusher.hpa.targetMemoryUtilizationPercentage}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.datapusher.hpa.targetMemoryUtilizationPercentage }}
  {{ end }}
{{ end }}