{{- if and .Values.frontend.spot.enabled .Values.frontend.spot.hpa.enable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.general.projectId }}-frontend-spot-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.general.projectId }}-frontend-spot

  minReplicas: {{ .Values.frontend.spot.hpa.minReplicas | default 0 }}
  maxReplicas: {{ .Values.frontend.spot.hpa.maxReplicas | default 3 }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.spot.hpa.cpuTarget | default 60 }}

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.spot.hpa.memoryTarget | default 75 }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60

    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
{{- end }}
