{{ if .Values.ingress.enableExternalCertificate }}
{{ if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: extensions/v1
{{ end }}
kind: Ingress
metadata:
  name: {{ .Values.general.projectId }}-ingress-external-certificate
  labels:
    app: {{ .Values.general.projectId }}-external-certificate
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass | quote | default "nginx-production" }}
    {{ if .Values.giftless.enable }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /_giftless;
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.proxyConnectTimeout | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.proxyReadTimeOut | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | default "1000M" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{ if .Values.ingress.extraAnnotations }}
    {{ with .Values.ingress.extraAnnotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
    {{ end }}
spec:
  {{ if .Values.ingress.externalCertificate.tls }}
  tls:
    {{ range .Values.ingress.externalCertificate.tls }}
    {{ if .isExternal }}
    - hosts:
        {{ range .hosts }}
        - {{ . | quote }}
        {{ end }}
      secretName: {{ .secretName }}
    {{ end }}
    {{ end }}
  {{ end }}
  rules:
    {{ range .Values.ingress.externalCertificate.hosts }}
    {{ if .isExternal }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{ range .paths }}
          - path: {{ .path }}
            pathType: prefix
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{ end }}
    {{ end }}
    {{ end }}
{{ end }}
