{{- if .Values.ckanmiddleware.enable -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.general.projectId }}-ingress-ckanmiddleware
  annotations:
    {{- if .Values.general.useProductionCerts }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote | default "letsencrypt-production" }}
    {{- else }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote | default "letsencrypt-staging" }}
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass | quote | default "nginx-production" }}
    {{ if .Values.giftless.enable }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /_giftless;
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ckanmiddleware.ingress.proxyReadTimeOut | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ckanmiddleware.ingress.proxyConnectTimeout | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ckanmiddleware.ingress.proxyBodySize | default "1000M"}}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{ if .Values.ckanmiddleware.ingress.extraAnnotations }}
    {{ with .Values.ckanmiddleware.ingress.extraAnnotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
    {{ end }}
spec:
  {{- if .Values.ckanmiddleware.ingress.tls }}
  tls:
    {{- range .Values.ckanmiddleware.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ckanmiddleware.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
    {{- end }}
{{- end }}
