{{ if .Values.ingress.enableExternal }}
{{ if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ .Values.general.projectId }}-ingress-external
  labels:
    app: {{ .Values.general.projectId }}-external
  annotations:
    {{ if .Values.general.useProductionCerts }}
    cert-manager.io/cluster-issuer: letsencrypt-production-external
    {{ else }}
    cert-manager.io/cluster-issuer: letsencrypt-staging-external
    {{ end }}
    kubernetes.io/ingress.class: nginx-production
    {{ if .Values.giftless.enable }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /_giftless;
    {{ end }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{ .Values.ingress.proxyConnectTimeout | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.ingress.proxyReadTimeOut | default 60 }}"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | default "1000M" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{ if .Values.ingress.extraAnnotations }}
    {{ with .Values.ingress.extraAnnotations }}
    {{ toYaml . | nindent 4 }}
    {{ end }}
    {{ end }}
spec:
  {{ if .Values.ingress.external.tls }}
  tls:
    {{ range .Values.ingress.external.tls }}
    {{ if .isExternal }}
    - hosts:
        {{ range .hosts }}
        - {{ . | quote }}
        {{ end }}
      secretName: {{ .secretName }}
    {{ end }}
    {{ end }}
  {{ end }}
  rules:
    {{ range .Values.ingress.external.hosts }}
    {{ if .isExternal }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{ range .paths }}
          - path: {{ .path }}
            backend:
              {{ if $.Values.general.maintenance }}
              serviceName: maintenance-svc
              servicePort: 80            
              {{ else }}
              serviceName: {{ .service }}
              servicePort: {{ .port }}
              {{ end }}
          {{ end }}
    {{ end }}
    {{ end }}
{{ end }}
