{{- if .Values.xloader.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.projectId }}-xloader-svc
spec:
  ports:
  - port: {{ .Values.xloader.port | default 80 }}
    targetPort: {{ .Values.xloader.targetPort | default 8000 }}
  selector:
    app: xloader
{{ end }}
