{{- if and .Values.xloader.enable .Values.xloader.hpa.enable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.general.projectId }}-xloader-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.general.projectId }}-xloader

  minReplicas: {{ .Values.xloader.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.xloader.hpa.maxReplicas | default 5 }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.xloader.hpa.cpuTarget | default 60 }}

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.xloader.hpa.memoryTarget | default 75 }}

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60

    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
{{- end }}
