{{- if and .Values.general.useSealedSecrets .Values.ckan.env }}
{{- include "ckan.validateSealedData" (dict "data" .Values.ckan.env "path" "ckan.env") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-ckan-envvars"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  {{- with .Values.ckan.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-ckan-envvars"
    type: Opaque
{{- end }}