{{- if and .Values.general.useSealedSecrets .Values.general.dockerconfigjson }}
{{- include "ckan.validateSealedData" (dict "data" (dict "dockerconfigjson" .Values.general.dockerconfigjson) "path" "general") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.general.imagePullSecrets }}
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.general.dockerconfigjson | quote }}
  template:
    metadata:
      name: {{ .Values.general.imagePullSecrets }}
    type: kubernetes.io/dockerconfigjson
{{- end }}