{{- if .Values.general.useSealedSecrets }}
{{- if .Values.ingress.enableExternalCertificate }}
{{- range .Values.ingress.externalCertificate.hosts }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ .tlsSecret.name }}
spec:
  encryptedData:
    tls.crt: {{ .tlsSecret.crt | quote }}
    tls.key: {{ .tlsSecret.key | quote }}
  template:
    metadata:
      name: {{ .tlsSecret.name }}
    type: kubernetes.io/tls
---
{{- end }}
{{- end }}
{{- end }}