{{- if and .Values.general.useSealedSecrets (and .Values.giftless.enable .Values.giftless.env) }}
{{- include "ckan.validateSealedData" (dict "data" .Values.giftless.env "path" "giftless.env") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-giftless-envvars"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  {{- with .Values.giftless.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-giftless-envvars"
    type: Opaque
{{- end }}