{{- if and .Values.general.useSealedSecrets (and .Values.giftless.enable .Values.giftless.env) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.general.projectId }}-giftless-config"
spec:
  {{- with .Values.giftless.env }}
  encryptedData:
    giftless.yaml: {{ .GIFTLESS_YAML_CONTENT | quote }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-giftless-config"
    type: Opaque
{{- end }}