{{- if and .Values.general.useSealedSecrets (hasKey .Values.ckan "redisConfig") }}
{{- if .Values.ckan.redisConfig.sealedPassword }}
{{- include "ckan.validateSealedData" (dict "data" (dict "sealedPassword" .Values.ckan.redisConfig.sealedPassword) "path" "ckan.redisConfig") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-redis-secret"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  encryptedData:
    redis-password: {{ .Values.ckan.redisConfig.sealedPassword | quote }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-redis-secret"
    type: Opaque
{{- end }}
{{- end }}