{{- if .Values.general.useSealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.ckan.general.projectId }}-redis-secret"
spec:
  encryptedData:
    redis-password: {{ .Values.ckan.redisConfig.sealedPassword | quote }}
  template:
    metadata:
      name: "{{ .Values.ckan.general.projectId }}-redis-secret"
    type: Opaque
{{- end }}