{{ if .Values.frontend.enable }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.general.projectId }}-frontend-sealed-envvars"
spec:
  encryptedData:
    API_KEY: {{ .Values.frontend.env.API_KEY }}
    API_URL: {{ .Values.frontend.env.API_URL }}
    DATA_SUBSCRIPTIONS_API_URL: {{ .Values.frontend.env.DATA_SUBSCRIPTIONS_API_URL }}
    GA_ID: {{ .Values.frontend.env.GA_ID }}
    KRATOS_ADMIN_URL: {{ .Values.frontend.env.KRATOS_ADMIN_URL }}
    KRATOS_PUBLIC_URL: {{ .Values.frontend.env.KRATOS_PUBLIC_URL }}
    NODE_ENV: {{ .Values.frontend.env.NODE_ENV }}
    PLUGINS: {{ .Values.frontend.env.PLUGINS }}
    PORT: {{ .Values.frontend.env.PORT | quote }}
    SECURITY_MODE: {{ .Values.frontend.env.SECURITY_MODE }}
    SESSION_COOKIE_MAX_AGE: {{ .Values.frontend.env.SESSION_COOKIE_MAX_AGE | quote }}
    SESSION_SECRET: {{ .Values.frontend.env.SESSION_SECRET }}
    SITE_URL: {{ .Values.frontend.env.SITE_URL }}
    THEME: {{ .Values.frontend.env.THEME }}
    WP_BLOG_PATH: {{ .Values.frontend.env.WP_BLOG_PATH }}
    WP_SHOW_DRAFT: {{ .Values.frontend.env.WP_SHOW_DRAFT }}
    WP_TOKEN: {{ .Values.frontend.env.WP_TOKEN | quote }}
    WP_URL: {{ .Values.frontend.env.WP_URL }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-frontend-sealed-envvars"
    type: Opaque

{{ end }}
