{{- if and .Values.general.useSealedSecrets (and .Values.auth.enable .Values.auth.env) }}
{{- include "ckan.validateSealedData" (dict "data" .Values.auth.env "path" "auth.env") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-auth-envvars"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  {{- with .Values.auth.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-auth-envvars"
    type: Opaque
{{- end }}