{{- if and .Values.general.useSealedSecrets (and .Values.frontend.enable .Values.frontend.env) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.general.projectId }}-frontend-envvars"
spec:
  {{- with .Values.frontend.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-frontend-envvars"
    type: Opaque
{{- end }}