{{ if .Values.auth.enable }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.general.projectId }}-auth-sealed-envvars"
spec:
  encryptedData:
    DSN: {{ .Values.auth.dsn }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-auth-sealed-envvars"
    type: Opaque
{{ end }}
