{{- if and .Values.general.useSealedSecrets (and .Values.frontend.enable .Values.frontend.env) }}
{{- include "ckan.validateSealedData" (dict "data" .Values.frontend.env "path" "frontend.env") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-frontend-envvars"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  {{- with .Values.frontend.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-frontend-envvars"
    type: Opaque
{{- end }}