{{- if and .Values.general.useSealedSecrets .Values.xloader.env }}
{{- include "ckan.validateSealedData" (dict "data" .Values.xloader.env "path" "xloader.env") }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ .Values.general.projectId }}-xloader-envvars"
  {{- include "ckan.sealedSecretAnnotations" . | nindent 2 }}
spec:
  {{- with .Values.xloader.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-xloader-envvars"
    type: Opaque
{{- end }}