{{- if and .Values.general.useSealedSecrets .Values.xloader.env }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: "{{ .Values.general.projectId }}-xloader-envvars"
spec:
  {{- with .Values.xloader.env }}
  encryptedData:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      name: "{{ .Values.general.projectId }}-xloader-envvars"
    type: Opaque
{{- end }}