name: Continuous Deployment
on:
  push:
    branches:
      - 'v*'
jobs:
  CICD:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Setup env variables
      uses: FranzDiebold/github-env-vars-action@v2
    - name: Install Helm
      env:
        GITHUB_REF: ${{ env.GITHUB_REF }}
        HELM_VERSION: v3.6.3
      run: |
        curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh --version "${HELM_VERSION}"
        helm version --client && rm ./get_helm.sh

    - name: Deploy
      env:
        GITHUB_REF: ${{ env.GITHUB_REF }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "travis-ci-operator@null"
        git config --global user.name "travis-ci-operator"
        git remote set-url --push origin https://zelima:$GITHUB_TOKEN@github.com/datopian/dx-helm-ckan
        cd charts
        helm package ../ckan --version "${GITHUB_REF}"
        helm repo index --url https://raw.githubusercontent.com/datopian/dx-helm-ckan/master/charts/ .
        cd ..
        git checkout master
        git status
        git add charts/index.yaml charts/ckan-${GITHUB_REF}.tgz
        git commit -m"upgrade helm chart repo to CKAN chart${GITHUB_REF}"
        git push origin master
